import { test, expect, markKnownDefect } from '../../fixtures/api';
import { buildMessage, Expected } from '../../data/testData';
import {
  assertMatchesSchema,
  MessageDetailSchema,
  MessageListSchema,
  UnreadCountSchema,
} from '../../schemas/schemas';

/**
 * The message service is the odd one out in this platform, and the suite is
 * arranged to make that visible rather than to smooth it over.
 *
 * Three of its habits differ from the room and booking services next door: it
 * answers create with 200 rather than 201, it returns validation errors as a
 * bare array instead of wrapping them in {"errors": [...]}, and it requires no
 * token to read. The first two are documented in the tests that touch them; the
 * third is serious enough to have its own "known defects" block below.
 *
 * Nothing here asserts on a total - no inbox size, no unread count on its own.
 * The instance is public, so the only quantities this suite owns are the ones
 * attached to an id it created itself.
 */
test.describe('Messages', () => {
  test('The contact form accepts a message from an anonymous visitor', async ({
    anonymousMessages,
    messages,
    janitor,
  }) => {
    const payload = buildMessage();
    // Armed before the write, so a failing assertion below cannot leak it.
    janitor.register(`message "${payload.subject}"`, () =>
      messages.removeBySubjectAsync(payload.subject)
    );

    const response = await anonymousMessages.create(payload);
    // 200 and {"success": true}, not 201 with the created message. The id has to
    // be recovered by searching the inbox for the subject, which is why the
    // subject generated by buildMessage carries a unique suffix - see
    // MessageClient.createMessageAsync, which wraps this same dance.
    expect(response.status()).toBe(200);
    expect(await response.json()).toMatchObject({ success: true });

    const id = (await messages.listMessagesAsync()).find(
      (message) => message.subject === payload.subject
    )?.id;
    expect(id, 'the posted message should appear in the inbox').toBeDefined();
  });

  test('The inbox is readable without a token - documented as-is', async ({
    anonymousMessages,
  }) => {
    // Not the behaviour anyone would design, but it is the behaviour. The
    // security consequence is asserted separately under "known defects" below,
    // where it can fail loudly once it is fixed. This test records the current
    // contract so the rest of the suite can rely on it.
    const response = await anonymousMessages.list();

    expect(response.status()).toBe(200);
  });

  test('A message keeps everything it was sent with', async ({ messages, janitor }) => {
    const payload = buildMessage();
    const id = await messages.createMessageAsync(payload);
    janitor.register(`message ${id}`, () => messages.remove(id));

    const response = await messages.getById(id);

    expect(response.status()).toBe(200);
    const detail = assertMatchesSchema(MessageDetailSchema, await response.json(), 'Message detail');
    expect(detail).toMatchObject({
      messageid: id,
      name: payload.name,
      email: payload.email,
      phone: payload.phone,
      subject: payload.subject,
      description: payload.description,
    });
  });

  test('A new message arrives unread and can be marked read', async ({ messages, janitor }) => {
    const payload = buildMessage();
    janitor.register(`message "${payload.subject}"`, () =>
      messages.removeBySubjectAsync(payload.subject)
    );
    const id = await messages.createMessageAsync(payload);

    /**
     * Every assertion here is about this one message, never about a total.
     *
     * An earlier version compared the unread counter before and after, which
     * fails the moment anything else touches the inbox - and something always
     * does, since the instance is public and this suite's own workers run in
     * parallel. It duly failed with 19 before and 18 after. The read flag on a
     * known id is the only thing this test can honestly own.
     */
    const summaries = assertMatchesSchema(
      MessageListSchema,
      await (await messages.list()).json(),
      'Inbox'
    );
    expect(summaries.messages.find((message) => message.id === id)?.read).toBe(false);

    const marked = await messages.markRead(id);
    expect(marked.status()).toBe(202);

    // 202 is "accepted", not "done" - the flag is polled, never read once.
    await expect
      .poll(async () => (await messages.listMessagesAsync()).find((message) => message.id === id)?.read, {
        message: 'the message should become read after the 202',
      })
      .toBe(true);
  });

  test('The count endpoint reports unread messages, not all of them', async ({
    messages,
    janitor,
  }) => {
    const payload = buildMessage();
    janitor.register(`message "${payload.subject}"`, () =>
      messages.removeBySubjectAsync(payload.subject)
    );
    const id = await messages.createMessageAsync(payload);
    expect((await messages.markRead(id)).status()).toBe(202);
    await expect
      .poll(async () => (await messages.listMessagesAsync()).find((message) => message.id === id)?.read, {
        message: 'this message must be read before the count can prove anything',
      })
      .toBe(true);

    /**
     * The endpoint is named "count" but reports an unread badge, and the way to
     * prove that without owning the whole instance is to check the invariant:
     * whatever it returns must equal the number of unread rows in the inbox.
     *
     * An earlier version asserted "unread < total", which only holds while at
     * least one message is read - on a shared instance where everyone else's
     * messages sit unread, that is a coin flip, and it duly failed. Polled
     * because the two endpoints are read separately and other people keep
     * writing in between.
     *
     * The message marked read above is what makes the invariant meaningful: with
     * at least one read message in the inbox, "count equals the unread rows" can
     * only hold if the endpoint leaves read messages out - a count of everything
     * would be larger. Without it, all-unread would make both numbers the total.
     */
    await expect
      .poll(async () => {
        const inbox = await messages.listMessagesAsync();
        const unreadInInbox = inbox.filter((message) => !message.read).length;
        const reported = await messages.unreadCountAsync();
        return inbox.some((message) => message.id === id && message.read) && reported === unreadInInbox;
      })
      .toBe(true);

    const countBody = assertMatchesSchema(
      UnreadCountSchema,
      await (await messages.unreadCount()).json(),
      'Unread count'
    );
    expect(countBody.count).toBeGreaterThanOrEqual(0);
  });

  test('A deleted message is gone from the inbox', async ({ messages }) => {
    const id = await messages.createMessageAsync(buildMessage());

    const removal = await messages.remove(id);
    expect(removal.status()).toBe(202);

    // 202 is "accepted", not "done" - see the note in booking.spec.ts.
    await expect
      .poll(async () => (await messages.listMessagesAsync()).map((message) => message.id), {
        message: 'the deleted message should stop being listed',
      })
      .not.toContain(id);
  });
});

test.describe('Messages - known defects', () => {
  /**
   * The whole message service is readable by anyone.
   *
   * This is the most serious finding in the suite. /api/message lists every
   * enquiry, and /api/message/{id} returns the sender's name, e-mail address,
   * phone number and the full text of what they wrote - with no token at all.
   * The room and booking services in the same platform do require one, so this
   * is a missing guard on one service rather than a platform-wide design.
   *
   * Three endpoints, checked independently with soft assertions, so a partial
   * fix shows up in the report as the endpoints that are still open - rather
   * than the first failure hiding the other two.
   *
   * The detail endpoint is probed with a message this test created itself,
   * found through the authenticated inbox. An earlier version took the id from
   * the anonymous list - so the day the list was guarded, the detail check,
   * the one about personal data, would have been skipped without a word.
   */
  test('DEFECT: the inbox and its personal data are readable anonymously', async ({
    messages,
    anonymousMessages,
    janitor,
  }) => {
    const payload = buildMessage();
    janitor.register(`message "${payload.subject}"`, () =>
      messages.removeBySubjectAsync(payload.subject)
    );
    const id = await messages.createMessageAsync(payload);

    const statuses = {
      list: (await anonymousMessages.list()).status(),
      count: (await anonymousMessages.unreadCount()).status(),
      detail: (await anonymousMessages.getById(id)).status(),
    };
    const values = Object.values(statuses);
    const guarded = (status: number) => status === 401 || status === 403;

    markKnownDefect(
      {
        documented: values.every((status) => status === 200 || guarded(status)) && values.some((status) => status === 200),
        fixed: values.every(guarded),
      },
      'Known defect #3: the message service answers anonymous reads'
    );
    expect.soft(guarded(statuses.list), `inbox list answered ${statuses.list} without a token`).toBe(true);
    expect.soft(guarded(statuses.count), `unread count answered ${statuses.count} without a token`).toBe(true);
    expect.soft(
      guarded(statuses.detail),
      `message detail (guest e-mail and phone) answered ${statuses.detail} without a token`
    ).toBe(true);
  });
});

test.describe('Messages - validation', () => {
  test('Every broken field is reported in one response', async ({ anonymousMessages }) => {
    const response = await anonymousMessages.create({
      name: '',
      email: 'not-an-email',
      phone: '123',
      subject: 'ab',
      description: 'short',
    });

    expect(response.status()).toBe(400);

    /**
     * Note the shape: this service answers with a bare array, while the room
     * and booking services wrap theirs in {"errors": [...]}. Three services,
     * two error envelopes - a client has to special-case this one.
     */
    const errors = (await response.json()) as string[];
    expect(Array.isArray(errors), 'the message service returns a bare array').toBe(true);
    expect(errors).toEqual(
      expect.arrayContaining([
        Expected.messageNameBlank,
        Expected.messageEmailMalformed,
        Expected.messagePhoneLength,
        Expected.messageSubjectLength,
        Expected.messageBodyLength,
      ])
    );
  });

  test('A body one character under the minimum is refused', async ({ anonymousMessages }) => {
    const response = await anonymousMessages.create(
      buildMessage({ description: 'x'.repeat(19) })
    );

    expect(response.status()).toBe(400);
    expect(await response.json()).toEqual(
      expect.arrayContaining([Expected.messageBodyLength])
    );
  });

  test('A body exactly at the minimum is accepted', async ({ anonymousMessages, messages, janitor }) => {
    const payload = buildMessage({ description: 'x'.repeat(20) });
    janitor.register(`message "${payload.subject}"`, () =>
      messages.removeBySubjectAsync(payload.subject)
    );

    // The boundary either side of the same rule - 19 fails above, 20 passes
    // here. Testing only the middle of a range proves nothing about its edges.
    const response = await anonymousMessages.create(payload);

    expect(response.status()).toBe(200);
  });
});
